version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
     - 'postgres_data:/var/lib/postgresql/data'

  redis:
    image: redislabs/redismod
    volumes:
     - 'redis_data:/data'

  backend:
    stdin_open: true
    tty: true
    build:
      dockerfile: ./dev.Dockerfile
      context: ../../
    volumes:
      - '../../:/app'
    env_file:
      - './config.env'
    ports:
      - '8081:8081'

volumes:
  redis_data:
  postgres_data:
